spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/krowdpoping2
    username: jellybears2
    password: jellybears2
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/jellybears-springboot/
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: krowdpoping@gmail.com
    password: xbhe pdbv nkua czev
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true



#  web:
#    resources:
#      static-locations: file:src/main/resources/static/
  logging:
    level:
      root: info

image:
  image-dir: img