spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/KrowdPoping
    username: jellybears
    password: jellybears

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/thymeleaf-springboot/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  web:
    resources:
      static-locations: C:/thymeleaf-springboot/
  logging:
    level:
      root: info