spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/krowdpoping2
    username: jellybears2
    password: jellybears2
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: krowdpoping@gmail.com # SMTP 서버 로그인 아이디 (발신자)
    password: xbhepdbvnkuaczev # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory # 필수 아님
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

#  mvc:
#    static-path-pattern: /static/**
#mybatis.mapper-locations=classpath:/mybatis-mapper/**/*.xml
  # mapper.xml location Setting
mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/thymeleaf-springboot/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
  logging:
    level:
      root: info
#  web:
#    resources:
#      static-locations: C:/thymeleaf-springboot/
